management.endpoints.access.default=read-only
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.health.mongodb.enabled=false

api.api-url=${CHS_KAFKA_API_URL:http://localhost:8889}
api.api-key=${FILING_HISTORY_API_SUB_DELTA_KEY:chsApiKey}
api.document-api-url=${DOCUMENT_API_LOCAL_URL:http://localhost:8080}

spring.mongodb.uri=${MONGODB_URL:mongodb://mongo:27017/company_filing_history}
spring.mongodb.database=company_filing_history

feature.resource_changed_call.disabled=${RESOURCE_CHANGED_CALL_DISABLED:false}

server.port=${PORT:8081}

status.rules=status_field_rules.yml

spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.serialization.fail-on-empty-beans=false

# OpenTelemetry configuration
management.opentelemetry.enabled=${OTEL_LOG_ENABLED}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
